# ansible-playbook -i ~/Downloads/hosts ~/Dropbox/code/scripts/ansible_miniconda.yaml
- hosts: all
  
  remote_user: centos
  #become: yes
  #become_user: hdfs
  #become_method: su
  
  tasks:
  
  ########################################################
  #
  #   Current Python Version
  #
  ########################################################
  - name: Capture Python Version
    command: python --version
    register: python_version
  
  - debug: msg="{{ python_version.stderr }}"
  
  ########################################################
  #
  #   Current User
  #
  ########################################################
  - name: Capture Python Version
    command: whoami
    register: current_user
  
  - debug: msg="{{ current_user.stdout }}"
  
  ########################################################
  #
  #   Cleanup / Remove Existing MiniConda Env
  #
  ########################################################
  - name: Remove miniconda env in /opt
    become: yes
    become_user: root
    become_method: sudo
    command: rm -rf /opt/miniconda
  
  - name: Remove existing miniconda.sh
    become: yes
    become_user: root
    become_method: sudo
    command: rm -rf /tmp/miniconda.sh
  
  - name: Remove anaconda env in /opt
    become: yes
    become_user: root
    become_method: sudo
    command: rm -rf /opt/anaconda
  
  - name: Remove existing anaconda.sh
    become: yes
    become_user: root
    become_method: sudo
    command: rm -rf /tmp/anaconda.sh
  
  ########################################################
  #
  #   Install MiniConda
  #
  ########################################################
  - name: Download MiniConda
    command: wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh
    args:
      chdir: /tmp/
  
  - name: chmod file
    command: chmod +x /tmp/miniconda.sh
  
  - name: Install bzip2 (for Centos)
    become: yes
    become_user: root
    become_method: sudo
    command: yum install -y bzip2
  
  - name: Install MiniConda
    become: yes
    become_user: root
    become_method: sudo
    command: /tmp/miniconda.sh -b -p /opt/miniconda
  
  #- name: 
  #  command: export PATH="/opt/miniconda/bin:$PATH"
  
  ########################################################
  #
  #   Install Python MiniConda Packages
  #
  ########################################################
  - name: Install python packages
    become: yes
    become_user: root
    become_method: sudo
    command: "/opt/miniconda/bin/conda install {{ item }}"
    with_items:
      - numpy
      - pandas
    responses:
      Questions:
        - 'y'
  
  ########################################################
  #
  #   Install Anaconda 3.x
  #
  ########################################################
  - name: Download Anaconda
    command: wget https://repo.anaconda.com/archive/Anaconda3-5.1.0-Linux-x86_64.sh -O anaconda.sh
    args:
      chdir: /tmp/
  
  - name: chmod file
    command: chmod +x /tmp/anaconda.sh
  
  - name: Install bzip2 (for Centos)
    become: yes
    become_user: root
    become_method: sudo
    command: yum install -y bzip2
  
  - name: Install Anaconda
    become: yes
    become_user: root
    become_method: sudo
    command: /tmp/anaconda.sh -b -p /opt/anaconda
  
  #- name: 
  #  command: export PATH="/opt/anaconda/bin:$PATH"



##########################################################################################
#
# NOTES:
#
#   http://docs.ansible.com/ansible/latest/index.html
#
#   "command" is more secure than "shell". However, "shell" uses env variables. Some 
#   stream operations will also note work with "command", such as >, &, etc.
#
#
##########################################################################################

#ZEND
